project: "WeatherDiffSR3"
name: "ddpm-sr-v1"
phase: "train"
gpu_ids: [2]
distributed: false
path:
    log: "logs"
    results: "results"
    checkpoint: "checkpoint"
    resume_state: null
datasets:
    train:
        name: "SR3-WEATHER-train"
        mode: "HR"
        lr_path: "train_T2_V10_U10_d02_2017-2019_lr_npy"
        hr_path: "train_T2_V10_U10_d02_2017-2019_hr_npy"
        data_format: "npy"
        low_res: 64
        high_res: 128
        batch_size: 16
        num_workers: 8
        use_shuffle: true
    val:
        name: "SR3-WEATHER-val"
        mode: "HR"
        lr_path: "val_T2_V10_U10_d02_2019_2020_lr_npy"
        hr_path: "val_T2_V10_U10_d02_2019_2020_hr_npy"
        data_format: "npy"
        low_res: 64
        high_res: 128
        batch_size: 16
        use_shuffle: false
    test:
        name: "SR3-WEATHRE-test"
        mode: "HR"
        lr_path: "val_T2_V10_U10_d02_2019_2020_lr_npy"
        hr_path: "val_T2_V10_U10_d02_2019_2020_hr_npy"
        data_format: "png"
        low_res: 64
        high_res: 128
        batch_size: 16
        use_shuffle: false
model:
    which_model_G: "sr3"
    finetune_norm: false
    unet:
        in_channel: 6
        out_channel: 3
        inner_channel: 64
        channel_multiplier: [1, 1, 2, 2, 4, 4]
        attn_res: [16]
        res_blocks: 2
        dropout: 0.2
    beta_schedule:
        train:
            schedule: "linear"
            n_timestep: 2000
            linear_start: 0.0001
            linear_end: 0.02
        val:
            schedule: "linear"
            n_timestep: 2000
            linear_start: 0.0001
            linear_end: 0.02
    diffusion:
        image_size: 128
        channels: 3
        conditional: true
train:
    n_iter: 500000
    val_freq: 50000
    save_checkpoint_freq: 50000
    print_freq: 50000
    optimizer:
        type: "adam"
        lr: 0.0001
    ema_scheduler:
        step_start_ema: 5000
        update_ema_every: 1
        ema_decay: 0.9999
wandb:
    project: "WeatherDiffSR3"